repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: 3.2.1
    hooks:
    - id: commitizen
      stages:
      - commit-msg

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    - id: isort
      args:
      - --profile=black
      - --line-length=100

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    - id: black
      args: # arguments to configure black
      - --line-length=100

      # these folders won't be formatted by black
      - --exclude="""\.git |
        \.__pycache__|
        \.hg|
        \.mypy_cache|
        \.tox|
        \.venv|
        _build|
        buck-out|
        build|
        dist"""

  # flake8
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    - id: flake8
      args: # arguments to configure flake8
      # making isort line length compatible with black
      - "--max-line-length=100"
      - "--max-complexity=18"
      - "--select=B,C,E,F,W,T4,B9"
      - "--exclude=.git,__pycache__,.mypy_cache,.tox,.venv,_build,buck-out,build,dist"

      # these are errors that will be ignored by flake8
      # check out their meaning here
      # https://flake8.pycqa.org/en/latest/user/error-codes.html
      - "--ignore=E203,E266,E501,W503,F405,F403,F401,E402,W605"

  # Others pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace

  - repo: https://github.com/PyCQA/autoflake
    rev: v2.1.1
    hooks:
    - id: autoflake
      args:
      - --remove-unused-variables
      - --remove-all-unused-imports

  - repo: https://github.com/python-poetry/poetry
    rev: 1.4.0
    hooks:
      - id: poetry-check
      - id: poetry-lock
        language_version: python3.10
        args:
          - --check
